---
output: 
  pdf_document: 
    toc: yes
    number_sections: yes
---

# Introduction {#intro}

> *"We have become, by the power of a glorious evolutionary accident called intelligence, the stewards of life's continuity on earth. We did not ask for this role, but we cannot abjure it. We may not be suited to it, but here we are."*
>
> --- Stephen J. Gould

## Modern ecological problems

**This is a course about community ecology and not so much about population ecology.** Community ecology underpins the vast fields of biodiversity and biogeography, and concerns spatial scales from squares of meters to all of Earth. We can look at historical, contemporary, and future processes that have been implicated in shaping the distribution of life on our planet.

Community ecologists tend to analyse how multiple environmental factors act as drivers that influence the distribution of tens or hundreds of species. These data tend to often be messy (not in the sense of untidy data as per the 'tidyverse' definition of tidy data, but it can be that too!) and statistical considerations need to be understood within the context of the data available to us. This translates to errors of measurement and errors due to extreme values, the presence of a few very rare or very abundant species, autocorrelated residuals (due to repeated sampling, for example), collinearity, etc. These challenges make to application of 'basic' statistical approaches problematic, and a new branch of inferential and exploratory statistical needs to be followed. These approaches involve techniques that allow us to work with all the data at once, and because it can simultaneously analyse all the variables (multiple environmental drivers acting on multiple species at multiple places and across multiple times), this group of statistics is called 'multivariate statistics.' There are two main groups of multivariate statistics: 'classifications' and 'ordinations.' Classification generally concerns placing samples (species or environments) into groups or hierarchies of groups, while ordination is best suited for analyses that involve arranging samples along gradients. Often they complement each other, but we shall see later that each approach has its own strengths. Irrespective of the analysis, the data share a few characteristics.

Biodiversity: patterns and processes...

```{r echo=TRUE}
library(vegan)
plant <- read.csv("data/plantations.csv")
head(plant)
```

### Background: the IUCN definition of biodiversity

### Alpha-, beta-, and gamma-diversity

### Whittaker's concept of beta-diversity, and contemporary interpretations

### The relationship between alpha- and beta-diversity

### Historical, neutral, and niche theories

### Species assembly: turnover and nestedness-resultant beta diversity

### Global change (climate change etc.)

## Where do ecological data come from?

Information is all around us. It has existed before sentient humans began questioning "Life, the Universe and Everything." During these early times, humans often invented silly answers, especially during the time before the scientific age when the tools and ways of thinking about problems became available. Today we have access to the ways and means to question the world around us, and we may arrive at objective answers (which are hopefully no longer silly). This module concerns large amounts of quantitative data (information turned into numbers) about our world. These quantitative data have been collected over many hundreds of years (give examples of long data sets), and they continue to be collected at increasing rates, over increasing spatial scales, and at finer and finer resolution. And because of advanced deterministic general circulation models that offer a predictive capability, which may be coupled via an ecophysiological understanding of how plants and animals and things that are neither plants nor animals react to environmental stimuli, we may project how the biota may respond in the future.

Let us consider some of the sources of information (data) that we will be able to analyse and turn into knowledge using the tools available to the quantitative ecologist.

### Field sampling

### Historical data

### Remotely sensed data

### Modelled data (projections)

## What do we do with these data?

We follow the principles of reproducible research, and throughout we will implement and practice modern data analytical methods. These approaches concern i) data entry, ii) data management, iii) data-wrangling, iv) analysis, and v) reporting, and we shall discuss each under the next headings.

### Initial data entry

### Meta-data and data management

### Data-wrangling: pre-processing and quality assurance

### Analysis

### Reporting

## This module

Practical applications of the quantitative ecological methods will be applied to studying the patterning of species along gradients, and the classification of landscapes (based on plant and animal assemblages) into clusters using some measures of (dis-)similarity.
